#!/usr/bin/env npx tsx

/**
 * Visual Regression Testing Script
 *
 * This script:
 * 1. Scans all .svelte components for `preview` exports
 * 2. Generates a dev components page at /dev/components
 * 3. Starts the dev server if not already running
 * 4. Takes screenshots of each component group with Playwright
 *
 * Usage: pnpm visual-test
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative, basename, dirname } from 'node:path';
import { spawn, exec } from 'node:child_process';
import { promisify } from 'node:util';
import { chromium } from 'playwright';

const execAsync = promisify(exec);

const PROJECT_ROOT = join(import.meta.dirname, '..');
const COMPONENTS_DIR = join(PROJECT_ROOT, 'src/lib/components');
const OUTPUT_PAGE = join(PROJECT_ROOT, 'src/routes/dev/components/+page.svelte');
const SCREENSHOTS_DIR = join(PROJECT_ROOT, '.screenshots');
const DEV_SERVER_PORT = 5173;
const DEV_SERVER_URL = `http://localhost:${DEV_SERVER_PORT}`;

interface ComponentInfo {
	name: string;
	importPath: string;
	filePath: string;
	hasPreview: boolean;
}

/**
 * Recursively find all .svelte files in a directory
 */
async function findSvelteFiles(dir: string): Promise<string[]> {
	const files: string[] = [];

	async function scan(currentDir: string) {
		const entries = await readdir(currentDir, { withFileTypes: true });
		for (const entry of entries) {
			const fullPath = join(currentDir, entry.name);
			if (entry.isDirectory()) {
				await scan(fullPath);
			} else if (entry.name.endsWith('.svelte') && !entry.name.startsWith('+')) {
				files.push(fullPath);
			}
		}
	}

	await scan(dir);
	return files;
}

/**
 * Check if a component file has a preview export
 */
async function hasPreviewExport(filePath: string): Promise<boolean> {
	const content = await readFile(filePath, 'utf-8');
	// Look for <script module> with export const preview
	return /export\s+const\s+preview\s*[=:]/.test(content);
}

/**
 * Get component info from file path
 */
function getComponentInfo(filePath: string, hasPreview: boolean): ComponentInfo {
	const relativePath = relative(join(PROJECT_ROOT, 'src/lib/components'), filePath);
	const name = basename(filePath, '.svelte');
	const importPath = `$lib/components/${relativePath.replace(/\\/g, '/')}`;

	return {
		name,
		importPath,
		filePath,
		hasPreview
	};
}

/**
 * Generate the dev components page
 */
function generatePageContent(components: ComponentInfo[]): string {
	const componentsWithPreview = components.filter((c) => c.hasPreview);
	const componentsWithoutPreview = components.filter((c) => !c.hasPreview);

	const imports = componentsWithPreview
		.map((c) => `import ${c.name}, { preview as ${c.name}Preview } from '${c.importPath}';`)
		.join('\n\t');

	const previewsArray = componentsWithPreview.map((c) => `{ component: ${c.name}, preview: ${c.name}Preview }`).join(',\n\t\t');

	return `<!--
  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
  Generated by: pnpm visual-test

  This page displays all components with their preview variants
  for visual regression testing.
-->
<script lang="ts">
	import type { ComponentPreview } from '$lib/testing/preview.js';

	${imports}

	const previews: Array<{ component: any; preview: ComponentPreview }> = [
		${previewsArray}
	];

	const layoutClasses = {
		row: 'flex flex-wrap gap-4 items-start',
		column: 'flex flex-col gap-4',
		grid: 'grid grid-cols-2 md:grid-cols-3 gap-4'
	};

	const backgroundClasses = {
		light: 'bg-white',
		dark: 'bg-gray-900',
		checkered: 'bg-[repeating-conic-gradient(#e5e7eb_0%_25%,white_0%_50%)] bg-[length:20px_20px]'
	};
</script>

<svelte:head>
	<title>Component Preview | Dev</title>
</svelte:head>

<div class="min-h-screen bg-gray-100 p-4">
	<header class="mb-8">
		<h1 class="text-3xl font-bold text-gray-900">Component Preview</h1>
		<p class="text-gray-600 mt-2">
			{previews.length} component{previews.length === 1 ? '' : 's'} with preview data
		</p>
	</header>

	<div class="space-y-8">
		{#each previews as { component: Component, preview }}
			<section
				data-component={preview.name}
				class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"
			>
				<header class="px-4 py-3 border-b border-gray-200 bg-gray-50">
					<h2 class="text-lg font-semibold text-gray-900">{preview.name}</h2>
					{#if preview.description}
						<p class="text-sm text-gray-600 mt-1">{preview.description}</p>
					{/if}
				</header>

				<div
					class="p-4 {backgroundClasses[preview.background ?? 'light']}"
				>
					<div class={layoutClasses[preview.layout ?? 'row']}>
						{#each preview.variants as variant}
							<div class="flex flex-col gap-2 {variant.wrapperClass ?? ''}">
								<span class="text-xs font-medium text-gray-500 uppercase tracking-wide">
									{variant.label}
								</span>
								{#if preview.isolate}
									<!-- Isolated container: transform creates new containing block for fixed elements -->
									<div class="relative overflow-hidden rounded-lg border border-gray-200" style="transform: translateZ(0); height: 400px;">
										<Component {...variant.props}>
											{#if variant.slot}
												{variant.slot}
											{/if}
										</Component>
									</div>
								{:else}
									<div>
										<Component {...variant.props}>
											{#if variant.slot}
												{variant.slot}
											{/if}
										</Component>
									</div>
								{/if}
							</div>
						{/each}
					</div>
				</div>
			</section>
		{/each}
	</div>

	${
		componentsWithoutPreview.length > 0
			? `
	<footer class="mt-12 p-6 bg-amber-50 rounded-lg border border-amber-200">
		<h3 class="font-semibold text-amber-800">Components without preview data</h3>
		<p class="text-sm text-amber-700 mt-1">
			Add a <code class="bg-amber-100 px-1 rounded">&lt;script module&gt;</code> with
			<code class="bg-amber-100 px-1 rounded">export const preview</code> to include these:
		</p>
		<ul class="mt-3 text-sm text-amber-800 list-disc list-inside">
			${componentsWithoutPreview.map((c) => `<li>${c.name}</li>`).join('\n\t\t\t')}
		</ul>
	</footer>`
			: ''
	}
</div>
`;
}

/**
 * Check if dev server is running
 */
async function isDevServerRunning(): Promise<boolean> {
	try {
		const response = await fetch(DEV_SERVER_URL, { method: 'HEAD' });
		return response.ok || response.status === 404; // 404 is fine, means server is up
	} catch {
		return false;
	}
}

/**
 * Start the dev server and wait for it to be ready
 */
async function startDevServer(): Promise<() => void> {
	console.log('Starting dev server...');

	const devProcess = spawn('pnpm', ['dev'], {
		cwd: PROJECT_ROOT,
		stdio: ['ignore', 'pipe', 'pipe'],
		shell: true,
		detached: false
	});

	// Wait for server to be ready
	const maxWait = 30000;
	const startTime = Date.now();

	while (Date.now() - startTime < maxWait) {
		if (await isDevServerRunning()) {
			console.log('Dev server is ready');
			return () => {
				devProcess.kill();
			};
		}
		await new Promise((r) => setTimeout(r, 500));
	}

	devProcess.kill();
	throw new Error('Dev server failed to start within 30 seconds');
}

/**
 * Take screenshots of each component
 */
async function takeScreenshots(): Promise<string[]> {
	console.log('Launching browser...');
	const browser = await chromium.launch();
	// Mobile-first: iPhone 14 viewport
	const context = await browser.newContext({
		viewport: { width: 390, height: 844 },
		deviceScaleFactor: 2
	});
	const page = await context.newPage();

	console.log(`Navigating to ${DEV_SERVER_URL}/dev/components...`);
	await page.goto(`${DEV_SERVER_URL}/dev/components`, { waitUntil: 'networkidle' });

	// Wait a bit for any animations to settle
	await page.waitForTimeout(500);

	// Find all component sections
	const components = await page.locator('[data-component]').all();
	console.log(`Found ${components.length} component(s) to screenshot`);

	// Ensure screenshots directory exists
	if (!existsSync(SCREENSHOTS_DIR)) {
		await mkdir(SCREENSHOTS_DIR, { recursive: true });
	}

	const screenshotPaths: string[] = [];

	for (const component of components) {
		const name = await component.getAttribute('data-component');
		if (!name) continue;

		const screenshotPath = join(SCREENSHOTS_DIR, `${name}.png`);
		await component.screenshot({ path: screenshotPath });
		console.log(`  ✓ ${name}.png`);
		screenshotPaths.push(screenshotPath);
	}

	await browser.close();
	return screenshotPaths;
}

/**
 * Main entry point
 */
async function main() {
	console.log('🔍 Scanning for components with previews...\n');

	// Find all svelte files
	const svelteFiles = await findSvelteFiles(COMPONENTS_DIR);
	console.log(`Found ${svelteFiles.length} component file(s)`);

	// Check each for preview export
	const components: ComponentInfo[] = [];
	for (const file of svelteFiles) {
		const hasPreview = await hasPreviewExport(file);
		components.push(getComponentInfo(file, hasPreview));
		if (hasPreview) {
			console.log(`  ✓ ${basename(file)} has preview`);
		}
	}

	const withPreview = components.filter((c) => c.hasPreview);
	if (withPreview.length === 0) {
		console.error('\n❌ No components with preview exports found.');
		console.error('Add a <script module> with "export const preview = {...}" to your components.');
		process.exit(1);
	}

	// Generate the page
	console.log('\n📝 Generating dev components page...');
	const pageContent = generatePageContent(components);

	// Ensure the route directory exists
	const routeDir = dirname(OUTPUT_PAGE);
	if (!existsSync(routeDir)) {
		await mkdir(routeDir, { recursive: true });
	}

	await writeFile(OUTPUT_PAGE, pageContent, 'utf-8');
	console.log(`  Written to: ${relative(PROJECT_ROOT, OUTPUT_PAGE)}`);

	// Check if dev server is running
	let stopServer: (() => void) | null = null;
	const serverRunning = await isDevServerRunning();

	if (!serverRunning) {
		stopServer = await startDevServer();
	} else {
		console.log('\n✓ Dev server already running');
	}

	try {
		// Take screenshots
		console.log('\n📸 Taking screenshots...');
		const screenshots = await takeScreenshots();
		console.log(`\n✅ Done! ${screenshots.length} screenshot(s) saved to .screenshots/`);
	} finally {
		if (stopServer) {
			console.log('\nStopping dev server...');
			stopServer();
		}
	}
}

main().catch((err) => {
	console.error('Error:', err);
	process.exit(1);
});
