<!--
  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
  Generated by: pnpm visual-test

  This page displays all components with their preview variants
  for visual regression testing.
-->
<script lang="ts">
	import type { ComponentPreview } from '$lib/testing/preview.js';

	import CharacterCard, { preview as CharacterCardPreview } from '$lib/components/character/CharacterCard.svelte';
	import CharacterSelector, { preview as CharacterSelectorPreview } from '$lib/components/character/CharacterSelector.svelte';
	import CharacterSelectorInline, { preview as CharacterSelectorInlinePreview } from '$lib/components/character/CharacterSelectorInline.svelte';
	import PhotoUpload, { preview as PhotoUploadPreview } from '$lib/components/character/PhotoUpload.svelte';
	import BottomSheet, { preview as BottomSheetPreview } from '$lib/components/layout/BottomSheet.svelte';
	import PageHeader, { preview as PageHeaderPreview } from '$lib/components/layout/PageHeader.svelte';
	import StickerDetail, { preview as StickerDetailPreview } from '$lib/components/sticker/StickerDetail.svelte';
	import StickerGrid, { preview as StickerGridPreview } from '$lib/components/sticker/StickerGrid.svelte';
	import StickerTile, { preview as StickerTilePreview } from '$lib/components/sticker/StickerTile.svelte';
	import Avatar, { preview as AvatarPreview } from '$lib/components/ui/Avatar.svelte';
	import Badge, { preview as BadgePreview } from '$lib/components/ui/Badge.svelte';
	import Button, { preview as ButtonPreview } from '$lib/components/ui/Button.svelte';
	import Card, { preview as CardPreview } from '$lib/components/ui/Card.svelte';
	import Input, { preview as InputPreview } from '$lib/components/ui/Input.svelte';
	import LoadingSpinner, { preview as LoadingSpinnerPreview } from '$lib/components/ui/LoadingSpinner.svelte';
	import Modal, { preview as ModalPreview } from '$lib/components/ui/Modal.svelte';
	import Toast, { preview as ToastPreview } from '$lib/components/ui/Toast.svelte';
	import Toaster, { preview as ToasterPreview } from '$lib/components/ui/Toaster.svelte';

	const previews: Array<{ component: any; preview: ComponentPreview }> = [
		{ component: CharacterCard, preview: CharacterCardPreview },
		{ component: CharacterSelector, preview: CharacterSelectorPreview },
		{ component: CharacterSelectorInline, preview: CharacterSelectorInlinePreview },
		{ component: PhotoUpload, preview: PhotoUploadPreview },
		{ component: BottomSheet, preview: BottomSheetPreview },
		{ component: PageHeader, preview: PageHeaderPreview },
		{ component: StickerDetail, preview: StickerDetailPreview },
		{ component: StickerGrid, preview: StickerGridPreview },
		{ component: StickerTile, preview: StickerTilePreview },
		{ component: Avatar, preview: AvatarPreview },
		{ component: Badge, preview: BadgePreview },
		{ component: Button, preview: ButtonPreview },
		{ component: Card, preview: CardPreview },
		{ component: Input, preview: InputPreview },
		{ component: LoadingSpinner, preview: LoadingSpinnerPreview },
		{ component: Modal, preview: ModalPreview },
		{ component: Toast, preview: ToastPreview },
		{ component: Toaster, preview: ToasterPreview }
	];

	const layoutClasses = {
		row: 'flex flex-wrap gap-4 items-start',
		column: 'flex flex-col gap-4',
		grid: 'grid grid-cols-2 md:grid-cols-3 gap-4'
	};

	const backgroundClasses = {
		light: 'bg-white',
		dark: 'bg-gray-900',
		checkered: 'bg-[repeating-conic-gradient(#e5e7eb_0%_25%,white_0%_50%)] bg-[length:20px_20px]'
	};
</script>

<svelte:head>
	<title>Component Preview | Dev</title>
</svelte:head>

<div class="min-h-screen bg-gray-100 p-4">
	<header class="mb-8">
		<h1 class="text-3xl font-bold text-gray-900">Component Preview</h1>
		<p class="text-gray-600 mt-2">
			{previews.length} component{previews.length === 1 ? '' : 's'} with preview data
		</p>
	</header>

	<div class="space-y-8">
		{#each previews as { component: Component, preview }}
			<section
				data-component={preview.name}
				class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"
			>
				<header class="px-4 py-3 border-b border-gray-200 bg-gray-50">
					<h2 class="text-lg font-semibold text-gray-900">{preview.name}</h2>
					{#if preview.description}
						<p class="text-sm text-gray-600 mt-1">{preview.description}</p>
					{/if}
				</header>

				<div
					class="p-4 {backgroundClasses[preview.background ?? 'light']}"
				>
					<div class={layoutClasses[preview.layout ?? 'row']}>
						{#each preview.variants as variant}
							<div class="flex flex-col gap-2 {variant.wrapperClass ?? ''}">
								<span class="text-xs font-medium text-gray-500 uppercase tracking-wide">
									{variant.label}
								</span>
								{#if preview.isolate}
									<!-- Isolated container: transform creates new containing block for fixed elements -->
									<div class="relative overflow-hidden rounded-lg border border-gray-200" style="transform: translateZ(0); height: 400px;">
										<Component {...variant.props}>
											{#if variant.slot}
												{variant.slot}
											{/if}
										</Component>
									</div>
								{:else}
									<div>
										<Component {...variant.props}>
											{#if variant.slot}
												{variant.slot}
											{/if}
										</Component>
									</div>
								{/if}
							</div>
						{/each}
					</div>
				</div>
			</section>
		{/each}
	</div>

	
</div>
